//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carshop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Carshop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Cars&gt;
        ///
        ///  &lt;Car id =&quot;1&quot; manufacturer=&quot;Opel&quot; model=&quot;Astra&quot; year=&quot;1995&quot;&gt;
        ///    &lt;Parts&gt;
        ///      &lt;Part id=&quot;1&quot; name=&quot;engine&quot; price=&quot;400&quot;&gt;&lt;/Part&gt;
        ///      &lt;Part id=&quot;2&quot; name=&quot;wheel&quot; price=&quot;30&quot;&gt;&lt;/Part&gt;
        ///      &lt;Part id=&quot;3&quot; name=&quot;turbine&quot; price=&quot;100&quot;&gt;&lt;/Part&gt;
        ///    &lt;/Parts&gt;
        ///  &lt;/Car&gt;
        ///
        ///  &lt;Car id =&quot;2&quot; manufacturer=&quot;Opel&quot; model=&quot;Astra&quot; year=&quot;2005&quot;&gt;
        ///    &lt;Parts&gt;
        ///      &lt;Part id=&quot;1&quot; name=&quot;engine&quot; price=&quot;600&quot;&gt;&lt;/Part&gt;
        ///      &lt;Part id=&quot;2&quot; name=&quot;wheel&quot; price=&quot;35&quot;&gt;&lt;/Part&gt;
        ///      &lt;Part id=&quot;3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Storehouse&gt;
        ///
        ///  &lt;Parts&gt;
        ///    &lt;Part car=&quot;1&quot; part=&quot;1&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;2&quot; part=&quot;2&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;3&quot; part=&quot;3&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;4&quot; part=&quot;4&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;5&quot; part=&quot;5&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;6&quot; part=&quot;4&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;1&quot; part=&quot;3&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;2&quot; part=&quot;2&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;3&quot; part=&quot;1&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;4&quot; part=&quot;2&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;5&quot; part=&quot;3&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car=&quot;6&quot; part=&quot;4&quot;&gt;&lt;/Part&gt;
        ///    &lt;Part car [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Storehouse {
            get {
                return ResourceManager.GetString("Storehouse", resourceCulture);
            }
        }
    }
}
